sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: aZpqcoQqAkts03dcEOlCbxlxT3nzL/w7y1+/9PaS2wqep+MoqLOF1eH8ACIlEnbekd5ppp7jefb2aBxMdGrtN+Ft9d0ko/k48di5v/812pIgiU+FLGOu7VmRPaOvOJqXA0QJ+5Mwai9Q7WBEDt7KLjv+sevw75C1Ub10RHlkrRJ5QbC/NH3vjAPfgYdhu6Y4MeUx0E4QFNS7hOXBPH4BnR7XQ6vFkgbZdRZlLO0Nqy3jHyOgmi9I62gUN12D3sb8LWe81VVfW6/B2ixwfLwr23FEwEnfidcBMU7zxkqf/cG5aHlCFnDe72NFmi46EIZnKp5C0AZdbO0Mo2J7/DlawJ/dPgfnK9aOZzf2drk4I6B1An4EzwSbynqnDTYr8odigtRI/B0teylhNjwTmphkVjjyK9GUVV81orWyewm89/BQrxtDMcquCGqwdeBrkVUFdYDQtZHyKm3qKcPF41JkxEPvSbm21GqUalPShRVRl+Gzzr0QR+ucPcQ01F/nc0o8m232Dx27cRYG24+P2UcoOLBs1zoiaa9lo8gL3pXIq+Vw3nPlH7jNnYvZYZm08jzAaO7y9puFyi8NOARdR3M1gQ3/owAyDCXJ8GwSN0TbP8sCOL7qL0bzacwbAn2EgxPmfhOjvFu6sgBsY0Pld1gayNUzfSh0hFFj7jw1Xa+cCsY=
  - secure: Y/LIdgyBJ/arwgccc4LlimTRjIa9+b7GxhWmhis4/sqljAHU07XXGEEGAn065fRpAyKcs8Q3lz6Fb6swib1RvZfwZD72WXOFbimegS02BHbO6n/wYUZVfZHPQMpRh/l2RX5qXCUWY6JwABKhX6TClfJnctLKCh48nL7nEC53OluUm98/l6XlfG4FNYsgO3P1dm/i08m+tslRX8vLImmNXXwPFUGzWbdFHy4KMxpUAYPBJqGHTeCFP641sDaZAnyxESNdxwReZGNz4I7adRaPgDo7WBodCBazSuCt3PIHqcW3xJSHi7nOVcm8GXoEi/CBQfCbIqOzG/GusyAhuHOsRbG6WudIn6qSpe8uqJXFYN7GdHJnJFbr+TvujOv16D+oW8l3rCzkl2Dng4S2pKC0erFuOBGNgNfeZkELcojI6ombezUr+2Nwn7rGdrB3j1swee6ByP4wmlFIHMD/IkANoVh9nqVaAARumZGJ/qlgGa9JHjkZX4b15Ma8KG0TvSOzaBJaatbJH1ESo3Yn0BayGnO60ztMtZyxCJLju9bc+rOL+8/nv3pTFrYQ4PQOBCPJwg+/H5NGyp0I8JpburAu/vWZpqSLTck5CYsfesX0EzdR6RUbaKV2ef/kKKMt9VqhEywONF9OdEAywoBOiXkZB0YZAUXpSEK7hAU4DoGz4GE=
  - secure: f+NHiy+4XBPb5aIGfk683k6o4GAdp3Lzhjtn+dy5IqCXvsrMSW1oA982qdHfJfALltTnrul8pwvPm3kY1wimYcsGErQEP9KWgwldLbiQVdPHR+kM2vg1hJAuyvb643XNTBBoi+8B/EEazXAIz7Zp3Y2mPd02vVfBM0QYQ3eYZC5MkUpx3G9iNHI8Kr9kwNFOQXdUPkiB5fOXVlmO0cPM5XynHDVnI1k3Y1N5ouLP6RoYFMlwDXBY1ifb4KyH09qZYhCiTnpDC1CSLGmB/5YFYm4b9U0vO80YYxG6MBJvg8LcE5Yvtr4qip7jDHL3MA3IOKRLtNssKTejX8Z+Dhu5yERlhxf6MSIeKiiPE9rEehvZTbOo2L8mu0653KCJ4EXibPPjl9piNqt/opGQpFpWJpFSeUruP3MDh79d0MS51RURCOnsmWJNE4TRPqvKLA/4fHPhgky9E9vta/98YllFkiL+UIOwjYadVZMNQi/z4DpvX5ABO4B0aPHizxB3fWEL433ixpnZaFE7TnCCfFKdsNzx5ZmcBfkDs0Wjf7j7sSjxsq2ClHzM1siHCTQp9SElxsJLb7N3QPgPhcCt+ne33HFrN7Hv1+QfiK1Rs0sHUhuWGZMYLljBHD0l9fcSNwPGuuHVvl1c6Evyshuwhg46TW7OxrK4s4l7zD4vFvSpRFs=
  - secure: h/PPgMOSgAIv6b3D5PCm11ZlSNIiK98u6dcOTOAn2coN2WpSEqJTxDLQuzOovngX0liMr3e40aydeb3IOx168bcdnFeDN/kmxDVTbcYbgkxm7staJaVpEzi3jLG1vaa03xeLxxLor2g4YxvzrHuzV2Cjy4vqKqjSBkUhdUbj1sJQbz6aL9B0N9vReEypFKWZ3kKphuy17XWEqGF64b6s17yFDjTg20BUSqZYeGR1CAJE2QqcKXNSo7Kv84TqDIipP67vhRaFywBCk0YpCsSGx7ur58P3BOPQLOOArcXSEf2kqg7HenqOwmR0n2yHPDLicjr3L7VtjL85j94xM8dGkPiZwt9ogwO+kNlVkmRrgwCb1LuKMJUCDpXC7YVcOFtEJ955pl4rBvnYEV0Rs58HTqqCp1R4NE0yKVDIXsLAjzLRAISiwTfb0UDZWI2u3pI6KQNGHRVG27J/CZfmWxZg+WdiL8nV0P4ay2Ov0vjuZ3SWbVwrSpHRYEuO+BjrPTfROAvu+Q2SBYsEJRkqf8yzVhktdfL3bKOA5Ahchy7ivRPJpXZvaTNvQWUmj/PcIGE+egwGRyNlNzGjWdKXcZULI3ihKdSBKdwmbSNL9kN1+Pvp3T1i7avwKYOOOSSOQkdjUZhGm7dkMpNU7R8SYXPEVr0LmC2Az6bGihfG9j4+e3Q=
